### ISSUE TITLE
Handling mal-formated output in scoring functions.

### ISSUE THREAD

**Issue by exoji2e** [exoji2e/hashcode-template#10]
What seems like a good approach? 
- raising errors 
- log errors and give score = 0 back?

I think we want to be able to do both, what if our solution sometimes does not produce a valid output, we might not want everything to crash..

**Comment by ahnlabb** [comment]
This is an important question. I believe that a reasonable solution would be to let the  `score` function raise an exception that is caught and handled in main.py but maybe just allowed to crash when the score module is run.

However is there a reasonable scenario where the output would be sporadically incorrect? If not, we probably want to fail quickly so that any errors can be found and valuable time isn't wasted.

**Comment by exoji2e** [comment]
Maybe we are overengineering this, but it looks good. I'll merge and we'll have to test if we actually want to use it :)
